#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script para traduzir a seção pt_BR do arquivo translation.dart
"""

import re

# Dicionário de traduções (apenas as principais - você pode expandir)
translations = {
    "Search": "Buscar",
    "Pick-up": "Retirada",
    "Confirm": "Confirmar",
    "Favourites": "Favoritos",
    "Clear": "Limpar",
    "What make of vehicle is it?": "Qual é a marca do veículo?",
    "Continue": "Continuar",
    "What model of vehicle is it?": "Qual é o modelo do veículo?",
    "What service location you want to register?": "Qual local de serviço você deseja registrar?",
    "What type of vehicle is it?": "Qual é o tipo de veículo?",
    "What color of vehicle is it?": "Qual é a cor do veículo?",
    "Vehicle Number": "Número do Veículo",
    "Enter Your Vehicle Number": "Digite o número do seu veículo",
    "What is the Vehicle's model year": "Qual é o ano do modelo do veículo?",
    "Apply Referral": "Aplicar Indicação",
    "Enter Referral Code": "Digite o código de indicação",
    "Apply": "Aplicar",
    "Manage Documents": "Gerenciar Documentos",
    "Passport": "Passaporte",
    "Not Uploaded": "Não Enviado",
    "Uploaded": "Enviado",
    "Upload": "Enviar",
    "Verification Pending": "Verificação Pendente",
    "Your document is still pending for verification. Once it's all verified you start getting rides. Please sit tight": "Seu documento ainda está pendente de verificação. Uma vez verificado, você começará a receber corridas. Por favor, aguarde",
    "Upload Documents": "Enviar Documentos",
    "Choose Language": "Escolher Idioma",
    "Enter your Vehicle Model Year": "Digite o ano do modelo do veículo",
    "Enter Your Vehicle Color": "Digite a cor do veículo",
    "Update Documents": "Atualizar Documentos",
    "Account Blocked": "Conta Bloqueada",
    "Your Account is blocked for the following reasons": "Sua conta está bloqueada pelos seguintes motivos",
    "Contact your Admin": "Entre em contato com o administrador",
    "Please Enable Your Location": "Por favor, ative sua localização",
    "Ok": "Ok",
    "Allow Location all the time - To book a taxi": "Permitir localização sempre - Para reservar um táxi",
    "On Duty": "Em Serviço",
    "Off Duty": "Fora de Serviço",
    "Pickup point": "Ponto de retirada",
    "Dropout point": "Ponto de destino",
    "Decline": "Recusar",
    "Accept": "Aceitar",
    "Call": "Ligar",
    "Chat": "Conversar",
    "Cancel": "Cancelar",
    "Arrived": "Chegou",
    "You are Online now": "Você está online agora",
    "You are Offline now": "Você está offline agora",
    "Arriving": "Chegando",
    "Way to Drop": "Caminho para o destino",
    "Start Ride": "Iniciar Corrida",
    "End Trip": "Finalizar Viagem",
    "Enter OTP": "Digite o OTP",
    "Enter the OTP displayed in Customer's App to start the ride": "Digite o OTP exibido no aplicativo do cliente para iniciar a corrida",
    "History": "Histórico",
    "Wallet": "Carteira",
    "Referal": "Indicação",
    "FAQ": "Perguntas Frequentes",
    "SOS": "SOS",
    "Change Language": "Alterar Idioma",
    "About": "Sobre",
    "Logout": "Sair",
    "Trip Summary": "Resumo da Viagem",
    "Reference Number": "Número de Referência",
    "Type of Ride": "Tipo de Corrida",
    "Distance": "Distância",
    "Duration": "Duração",
    "Fare Breakup": "Detalhamento da Tarifa",
    "Base Price": "Preço Base",
    "Taxes": "Impostos",
    "Distance Price": "Preço por Distância",
    "Time Price": "Preço por Tempo",
    "Cancellation Fee": "Taxa de Cancelamento",
    "Convenience Fee": "Taxa de Conveniência",
    "Total Fare": "Tarifa Total",
    "Cash": "Dinheiro",
    "Trusted Contact": "Contato Confiável",
    "Share your trip status": "Compartilhar status da sua viagem",
    "Youâ€™ll be able to share your live location with one or more contacts during any trip": "Você poderá compartilhar sua localização em tempo real com um ou mais contatos durante qualquer viagem",
    "Set your emergency contacts": "Definir seus contatos de emergência",
    "You can make a trusted contact an emergency contact": "Você pode tornar um contato confiável um contato de emergência",
    "Add trusted contact": "Adicionar contato confiável",
    "Submit": "Enviar",
    "Give your Feedback": "Dê seu feedback",
    "Testing": "Testando",
    "Cancel Reason": "Motivo do Cancelamento",
    "Cancel Request": "Cancelar Solicitação",
    "Enter Cancel Reason": "Digite o motivo do cancelamento",
    "Choose Drop Location": "Escolher local de destino",
    "Choose Pick Location": "Escolher local de retirada",
    "Favourite Address": "Endereço Favorito",
    "Pickup Suggestion": "Sugestão de Retirada",
    "Drop Suggestion": "Sugestão de Destino",
    "Locate on Map": "Localizar no Mapa",
    "Enter 4 letters to search destination": "Digite 4 letras para buscar destino",
    "Suggested Rides": "Corridas Sugeridas",
    "Payment Method": "Método de Pagamento",
    "Choose your payment now or later": "Escolha seu pagamento agora ou depois",
    "Pay when trip ends": "Pagar quando a viagem terminar",
    "For seamless and contact less payment": "Para pagamento sem complicação e sem contato",
    "For faster payment": "Para pagamento mais rápido",
    "For Instant payment": "Para pagamento instantâneo",
    "Paying via": "Pagar via",
    "Enter Promo Code": "Digite o código promocional",
    "Remove": "Remover",
    "Edit": "Editar",
    " Coupon Applied": " Cupom Aplicado",
    "Invalid Coupon Code": "Código de Cupom Inválido",
    "Looking for nearby drivers": "Procurando motoristas próximos",
    "We Are Looking For Nearby Captain To Accept Your Ride. Once Accepted You Can Ride With Us! We Appreciate Your Patience!": "Estamos procurando um capitão próximo para aceitar sua corrida. Uma vez aceita, você pode viajar conosco! Agradecemos sua paciência!",
    "Any Instructions for pick up": "Alguma instrução para retirada",
    "Share Ride": "Compartilhar Corrida",
    "Are you sure to cancel ride": "Tem certeza de que deseja cancelar a corrida",
    "Your ride will be cancelled and returned to main menu. This will lead to cancellation fee": "Sua corrida será cancelada e retornará ao menu principal. Isso resultará em taxa de cancelamento",
    "Don't Cancel": "Não Cancelar",
    "Reason for cancelling ride": "Motivo para cancelar a corrida",
    "No Driver Found": "Nenhum Motorista Encontrado",
    "Try Again": "Tentar Novamente",
    "Ride Later": "Corrida Depois",
    "Ride Now": "Corrida Agora",
    "Home": "Casa",
    "Work": "Trabalho",
    "Others": "Outros",
    "Enter Favourites Name": "Digite o nome do favorito",
    "Are you sure to choose ride in this time": "Tem certeza de escolher corrida neste horário",
    "Ride is confirmed successfully": "Corrida confirmada com sucesso",
    "Save as Favourite": "Salvar como Favorito",
    "Most Trusted Taxi Booking App": "Aplicativo de Reserva de Táxi Mais Confiável",
    "To enjoy your ride experience": "Para aproveitar sua experiência de viagem",
    "Please allow us the following permissions": "Por favor, permita-nos as seguintes permissões",
    "Allow": "Permitir",
    "Ride Cancelled by Driver": "Corrida Cancelada pelo Motorista",
    "Ride Cancelled Successfully": "Corrida Cancelada com Sucesso",
    "Notify Admin": "Notificar Administrador",
    "Notified Successfully": "Notificado com Sucesso",
    "Chat With Driver": "Conversar com o Motorista",
    "Enter Message": "Digite a mensagem",
    "New Message Received": "Nova Mensagem Recebida",
    "No Internet Connection": "Sem Conexão com a Internet",
    "Please check your internet connection, try enabling wifi or try again later": "Por favor, verifique sua conexão com a internet, tente ativar o wifi ou tente novamente mais tarde",
    "Copyrights": "Direitos Autorais",
    "Terms and Conditions": "Termos e Condições",
    "Your Trusted Contacts": "Seus Contatos Confiáveis",
    "Are you sure to remove this contact from your trusted Contact": "Tem certeza de remover este contato dos seus contatos confiáveis",
    "No Data Found": "Nenhum Dado Encontrado",
    "Are you sure to remove this address from your favorites": "Tem certeza de remover este endereço dos seus favoritos",
    "Invite": "Convidar",
    "Join me on 55! using my invite code": "Junte-se a mim no 55! usando meu código de convite",
    "To make easy your ride": "Para facilitar sua viagem",
    "Upcoming": "Próximas",
    "Completed": "Concluídas",
    "Cancelled": "Canceladas",
    "Card": "Cartão",
    "Load More": "Carregar Mais",
    "Location details": "Detalhes da localização",
    "Assigned": "Atribuído",
    "Started": "Iniciado",
    "Available Balance": "Saldo Disponível",
    "Add Money": "Adicionar Dinheiro",
    "Recent Transactions": "Transações Recentes",
    "Deposit": "Depósito",
    "Ride Payment": "Pagamento da Corrida",
    "Money Deposited": "Dinheiro Depositado",
    "Enter Amount Here": "Digite o valor aqui",
    "Edit Profile": "Editar Perfil",
    "Edit Image": "Editar Imagem",
    "Pay": "Pagar",
    "Something Went Wrong, Try again": "Algo deu errado, tente novamente",
    "Payment successful": "Pagamento bem-sucedido",
    "Camera": "Câmera",
    "Gallery": "Galeria",
    "Update Vehicle Info": "Atualizar Informações do Veículo",
    "Vehicle Make": "Marca do Veículo",
    "Vehicle Model": "Modelo do Veículo",
    "Vehicle Year": "Ano do Veículo",
    "Vehicle Type": "Tipo de Veículo",
    "Vehicle Color": "Cor do Veículo",
    "Tap here to upload": "Toque aqui para enviar",
    "Earnings": "Ganhos",
    "Today": "Hoje",
    "Weekly": "Semanal",
    "Monthly": "Mensal",
    "Trips": "Viagens",
    "Hours": "Horas",
    "Trip Kms": "Quilômetros da Viagem",
    "Wallet Payment": "Pagamento com Carteira",
    "Cash Payment": "Pagamento em Dinheiro",
    "Total Earnings": "Ganhos Totais",
    "Report": "Relatório",
    "From Date": "Data Inicial",
    "To Date": "Data Final",
    "Withdraw": "Sacar",
    "Withdraw History": "Histórico de Saques",
    "Withdraw Request At": "Solicitação de Saque em",
    "Bank Details": "Detalhes Bancários",
    "Account Holder Name": "Nome do Titular da Conta",
    "Account Number": "Número da Conta",
    "Bank Code": "Código do Banco",
    "Bank Name": "Nome do Banco",
    "Update Bank Info": "Atualizar Informações Bancárias",
    "Are you sure want to logout": "Tem certeza de que deseja sair",
    "Start Ride with OTP": "Iniciar Corrida com OTP",
    "Loading Localization": "Carregando Localização",
    "Enable Background Location - to give you ride request even if your app is in background": "Ativar Localização em Segundo Plano - para receber solicitações de corrida mesmo quando o aplicativo estiver em segundo plano",
    "Admin Commission For Trip": "Comissão do Administrador pela Viagem",
    "Trip Commission": "Comissão da Viagem",
    "Cancellation Fee": "Taxa de Cancelamento",
    "Money Deposited By Admin": "Dinheiro Depositado pelo Administrador",
    "Referral Commission": "Comissão de Indicação",
    "Spent For Trip Request": "Gasto na Solicitação de Viagem",
    "Withdrawn From Wallet": "Sacado da Carteira",
    "User Cancelled the Request": "Solicitação Cancelada pelo Usuário",
    "Your wallet balance is low, please add some money to continue service": "O saldo da sua carteira está baixo, por favor adicione algum dinheiro para continuar o serviço",
    "Please enter correct Otp or resend": "Por favor, digite o OTP correto ou reenvie",
    "Referral Code Copied": "Código de Indicação Copiado",
    "Allow Location": "Permitir Localização",
    "Your Wallet Balance is too low to make this ride": "O saldo da sua carteira está muito baixo para fazer esta corrida",
    "Internal Server Error": "Erro Interno do Servidor",
    "Supported Vehicles": "Veículos Suportados",
    "Description": "Descrição",
    "Estimated Amount": "Valor Estimado",
    "Location access is needed for running the app, please enable it in settings and tap done": "O acesso à localização é necessário para executar o aplicativo, por favor ative nas configurações e toque em concluído",
    "Open Settings": "Abrir Configurações",
    "Done": "Concluído",
    "Contact access is needed to pick contact for SOS, pleable enable it in settings and tap done": "O acesso aos contatos é necessário para escolher contato para SOS, por favor ative nas configurações e toque em concluído",
    "Camera access is needed to capture image, please enable it in settings and tap done": "O acesso à câmera é necessário para capturar imagem, por favor ative nas configurações e toque em concluído",
    "Photos access is needed to pick image, please enable it in settings and tap done": "O acesso às fotos é necessário para escolher imagem, por favor ative nas configurações e toque em concluído",
    "Enter Otp": "Digite o OTP",
    "Add by Card": "Adicionar por Cartão",
    "Add by Kiosk": "Adicionar por Quiosque",
    "Pay by Card": "Pagar por Cartão",
    "Pay by Kiosk": "Pagar por Quiosque",
    "Please enter valid OTP": "Por favor, digite um OTP válido",
    "Bill Reference": "Referência da Fatura",
    "Subscriptions": "Assinaturas",
    "Select a plan to continue": "Selecione um plano para continuar",
    "Spot payment to your wallet": "Pagamento pontual para sua carteira",
    "Benefits of getting whole amount": "Benefícios de obter o valor total",
    "Get priority customer support": "Obtenha suporte prioritário ao cliente",
    "0% commission": "0% de comissão",
    "Your Subscription is ended": "Sua assinatura terminou",
    "Your Subscription has ended on ": "Sua assinatura terminou em ",
    "Purchase now": "Comprar agora",
    "Browse Plans": "Navegar Planos",
    "Monthly Plan": "Plano Mensal",
    "Yearly Plan": "Plano Anual",
    "Ride Scheduled at": "Corrida Agendada em",
    "Cancel Ride": "Cancelar Corrida",
    "Subscribe a plan to continue getting rides": "Assine um plano para continuar recebendo corridas",
    "Make Complaint": "Fazer Reclamação",
    "Click Below to Choose Type": "Clique abaixo para escolher o tipo",
    "Write your complaint here": "Escreva sua reclamação aqui",
    "We Successfully Got Your Concern...": "Recebemos sua preocupação com sucesso...",
    "We Will Get You Sooner": "Entraremos em contato em breve",
    "Thank You": "Obrigado",
    "minimum 10 characters": "mínimo de 10 caracteres",
    "Try Free Trial for 1 Month": "Experimente o teste gratuito por 1 mês",
    "Are you sure to get Free Trial for 1 month": "Tem certeza de obter o teste gratuito por 1 mês",
    "Waiting Time": "Tempo de Espera",
    "mins": "min",
    "Free Waiting Time": "Tempo de Espera Gratuito",
    "Free Waiting Time Before Trip Start": "Tempo de Espera Gratuito Antes do Início da Viagem",
    "Free Waiting Time After Trip Start": "Tempo de Espera Gratuito Após o Início da Viagem",
    "Waiting Price": "Preço de Espera",
    "Discount": "Desconto",
    "Service not available in your location": "Serviço não disponível na sua localização",
    "Inclusive of TAX": "Incluindo impostos",
    "Surge fee": "Taxa de demanda",
    "Choose Payment Method": "Escolher Método de Pagamento",
    "Rental Ride": "Corrida de Aluguel",
    "Regular": "Regular",
    "Package Name": "Nome do Pacote",
    "please enter valid referral code": "por favor digite um código de indicação válido",
    "Driver arrives in": "Motorista chega em",
    "Please enter valid email address": "Por favor, digite um endereço de e-mail válido",
    "Delete Account": "Excluir Conta",
    "Are you sure want to delete your account": "Tem certeza de que deseja excluir sua conta",
    "Add Cancel Reason": "Adicionar Motivo de Cancelamento",
    "Chat with Passenger": "Conversar com Passageiro",
    "Available": "Disponível",
    "OnBoard": "A bordo",
    "Offline": "Offline",
    "No Data Found": "Nenhum Dado Encontrado",
    "Manage Vehicles": "Gerenciar Veículos",
    "Manage Drivers": "Gerenciar Motoristas",
    "Driver Added Successfully": "Motorista Adicionado com Sucesso",
    "No Driver ": "Sem Motorista ",
    "Assign new Driver +": "Atribuir novo Motorista +",
    "Please Select Driver": "Por favor, selecione o motorista",
    "Fleet Not Assigned": "Frota Não Atribuída",
    "No Drivers Found": "Nenhum Motorista Encontrado",
    "Select Date": "Selecionar Data",
    "User": "Usuário",
    "Driver": "Motorista",
    "Driver Not Assigned": "Motorista Não Atribuído",
    "Waiting For Approval": "Aguardando Aprovação",
    "No Vehicle Found": "Nenhum Veículo Encontrado",
    "Assign Driver": "Atribuir Motorista",
    "Upload Docs": "Enviar Documentos",
    "Vehicle Successfully Added": "Veículo Adicionado com Sucesso",
    "Add Photo": "Adicionar Foto",
    "Login as a Driver": "Entrar como Motorista",
    "Login as a Owner": "Entrar como Proprietário",
    "Fleet Details": "Detalhes da Frota",
    "Delete Driver": "Excluir Motorista",
    "Are you sure want to delete this driver ?": "Tem certeza de que deseja excluir este motorista?",
    "Yes": "Sim",
    "No": "Não",
    "Your owner wallet balance is low, please contact your owner": "O saldo da carteira do proprietário está baixo, por favor entre em contato com seu proprietário",
    "Add Vehicle": "Adicionar Veículo",
    "Address": "Endereço",
    "Add Driver": "Adicionar Motorista",
    "Choose Area": "Escolher Área",
    "Company Name": "Nome da Empresa",
    "City": "Cidade",
    "Postal Code": "Código Postal",
    "Tax Number": "Número de Imposto",
    "No Fleet Assigned": "Nenhuma Frota Atribuída",
    "Ride without Destination": "Corrida sem Destino",
    "Notification": "Notificação",
    "Are you sure want to Delete the Notication": "Tem certeza de que deseja excluir a notificação",
    "Share": "Compartilhar",
    "Share Money": "Compartilhar Dinheiro",
    "Close": "Fechar",
    "Fill The Fields": "Preencher os Campos",
    "Admin Commission": "Comissão do Administrador",
    "Notification  Deleted": "Notificação Excluída",
    "Transferred Successfully": "Transferido com Sucesso",
    "Account": "Conta",
    "General": "Geral",
    "Contact us": "Entre em contato",
    "No Order Here": "Nenhum Pedido Aqui",
    "Latest Transactions": "Últimas Transações",
    "Recharge Balance": "Recarregar Saldo",
    "Here you can top-up your wallet": "Aqui você pode recarregar sua carteira",
    "Transfer Money": "Transferir Dinheiro",
    "Today Earnings": "Ganhos de Hoje",
    "Start Add New Connection": "Começar a Adicionar Nova Conexão",
    "Add Connection Name": "Adicionar Nome da Conexão",
    "Enter The Name": "Digite o Nome",
    "Add Connection Number": "Adicionar Número da Conexão",
    "Enter The Phone Number": "Digite o Número do Telefone",
    "Help": "Ajuda",
    "You Can Contact Us": "Você Pode Entrar em Contato",
    "What's your mobile number ?": "Qual é o seu número de celular?",
    "You will get a sms for Verification": "Você receberá um SMS para verificação",
    "Enter the OTP number send to you at": "Digite o número OTP enviado para você em",
    "what's your name?": "qual é o seu nome?",
    "Let us know how we know probably address you": "Deixe-nos saber como devemos provavelmente chamá-lo",
    "Enter First Name": "Digite o Primeiro Nome",
    "Enter Last Name": "Digite o Sobrenome",
    "Enter Your Email Address": "Digite seu endereço de e-mail",
    "Accept Terms & Review Privacy Policy Notice": "Aceitar Termos e Revisar Aviso de Política de Privacidade",
    "By Selecting \"I Agree\" below, I have reviewed and agree to the Terms of Use and acknowledged the Privacy Notice.": "Ao selecionar \"Concordo\" abaixo, revisei e concordo com os Termos de Uso e reconheci o Aviso de Privacidade.",
    "I Agree": "Concordo",
    "Required Information": "Informações Obrigatórias",
    "Welcome": "Bem-vindo",
    "Here is what you need to become caption": "Aqui está o que você precisa para se tornar capitão",
    "Profile": "Perfil",
    "To accept the application, we need identification that prove the eligibility of the applicant to provide the service.": "Para aceitar a aplicação, precisamos de identificação que prove a elegibilidade do candidato para fornecer o serviço.",
    "Car Information": "Informações do Carro",
    "Document": "Documento",
    "Upload your photo and License": "Envie sua foto e Licença",
    "Upload Image": "Enviar Imagem",
    "Expiry Date": "Data de Validade",
    "Choose Expiry Date": "Escolher Data de Validade",
    "Please Fill Required Information": "Por favor, preencha as informações obrigatórias",
    "please choose image": "por favor escolha a imagem",
    "Car Type": "Tipo de Carro",
    "Make Name": "Nome da Marca",
    "Model Name": "Nome do Modelo",
    "Model Year": "Ano do Modelo",
    "Enter Vehicle Model Year": "Digite o Ano do Modelo do Veículo",
    "Please Enter Valid Date": "Por favor, digite uma data válida",
    "Enter Vehicle Number": "Digite o Número do Veículo",
    "Enter Vehicle Color": "Digite a Cor do Veículo",
    "Sign Out": "Sair",
    "Saved Address": "Endereço Salvo",
    "My Orders": "Meus Pedidos",
    "Total": "Total",
    "We are evaluating your profile": "Estamos avaliando seu perfil",
    "In order to make sure our community holds up a standard,we dont allow any profiles to get in.": "Para garantir que nossa comunidade mantenha um padrão, não permitimos que nenhum perfil entre.",
    "Kindly re-upload the required document": "Por favor, reenvie o documento obrigatório",
    "This step take between 2-24 hour": "Esta etapa leva entre 2-24 horas",
    "The Declined reason is": "O motivo da recusa é",
    "Profile Information": "Informações do Perfil",
    "Mobile Number": "Número do Celular",
    "Select Work Area": "Selecionar Área de Trabalho",
    "Work Area": "Área de Trabalho",
    "Select Vehicle Model": "Selecionar Modelo do Veículo",
    "Select Vehicle Make": "Selecionar Marca do Veículo",
    "Choose Date": "Escolher Data",
    "Delete": "Excluir",
    "Where do you want to go?": "Para onde você quer ir?",
    "View on map": "Ver no mapa",
    "Coupons": "Cupons",
    "Cancel Booking": "Cancelar Reserva",
    "Captain Nearby": "Capitão Próximo",
    "The captain will arrive within 2 minutes be ready to meet him": "O capitão chegará em até 2 minutos, esteja pronto para encontrá-lo",
    "Captain Has Arrived": "Capitão Chegou",
    "Captain has arrived. To avoid extra fees, be sure to meet your driver within 3 minutes": "O capitão chegou. Para evitar taxas extras, certifique-se de encontrar seu motorista em até 3 minutos",
    "Why do you want to cancel order?": "Por que você quer cancelar o pedido?",
    "Why Do You Want To Report This Trip?": "Por que você quer reportar esta viagem?",
    "We appriciate you helping us keep Our App safe": "Agradecemos sua ajuda para manter nosso aplicativo seguro",
    "Thanks for letting us now": "Obrigado por nos avisar",
    "This feedback is important in helping us keep\u000bOur App Community safe and secure for everyone": "Este feedback é importante para nos ajudar a manter nossa comunidade de aplicativos segura e protegida para todos",
    "Enter the OTP number send to you at ": "Digite o número OTP enviado para você em ",
    "Resend OTP Number": "Reenviar Número OTP",
    "Have Issue": "Tem Problema",
    "Most Trusted app": "Aplicativo mais confiável",
    "To enjoy your ride experience Please, us the following permission": "Para aproveitar sua experiência de viagem, por favor, nos dê a seguinte permissão",
    "Saved Places": "Locais Salvos",
    "Searching For Captain": "Procurando Capitão",
    "On The Way": "A Caminho",
    "On Ride": "Em Viagem",
    "Waiting for Customer": "Aguardando Cliente",
    "Contact Support": "Contatar Suporte",
    "By Selecting \" I Agree \" below, I have Reviewed and agree to the": "Ao selecionar \" Concordo \" abaixo, revisei e concordo com os",
    " Terms Of Use ": " Termos de Uso ",
    " and acknowledged the ": " e reconheci a ",
    "What would you to do today?": "O que você gostaria de fazer hoje?",
    "Take a Ride Now": "Fazer uma Viagem Agora",
    "Get Ready For Ride Later": "Prepare-se para Viagem Depois",
    "Now": "Agora",
    "Later": "Depois",
    "Door-To-Door": "Porta a Porta",
    "Convenience,Safety,": "Conveniência, Segurança,",
    "and Reliable Quality,": "e Qualidade Confiável,",
    "Or add your destination later ": "Ou adicione seu destino depois ",
    "No Captain Found": "Nenhum Capitão Encontrado",
    "Captain Is Waiting For You": "Capitão Está Esperando Por Você",
    "Back To Home Page": "Voltar à Página Inicial",
    "Add an Address": "Adicionar um Endereço",
    "Amount of": "Valor de",
    "has been transferred to": "foi transferido para",
    "Company Information": "Informações da Empresa",
    "Instant Taxi Ride": "Viagem de Táxi Instantânea",
    "My Route Booking": "Minha Reserva de Rota",
    "Home Address": "Endereço Residencial",
    "Add Home Address": "Adicionar Endereço Residencial",
    "Disable My Route Booking": "Desativar Minha Reserva de Rota",
    "Enable My Route Booking": "Ativar Minha Reserva de Rota",
    "Choose Home Address": "Escolher Endereço Residencial",
    "Address Added Successfully": "Endereço Adicionado com Sucesso",
    "Your current location should not be less than 5km from your home address": "Sua localização atual não deve estar a menos de 5km do seu endereço residencial",
    "Way to Drop in": "Caminho para o Destino em",
    "Please enter valid Referral Code": "Por favor, digite um código de indicação válido",
    "Shipment Load": "Carga do Envio",
    "Shipment Unload": "Descarga do Envio",
    "Instructions": "Instruções",
    "Add Instructions": "Adicionar Instruções",
    "Long press and move for switch address position": "Pressione e segure e mova para alternar a posição do endereço",
    "Choose Address for Navigation": "Escolher Endereço para Navegação",
    "Signature": "Assinatura",
    "Retry": "Tentar Novamente",
    "Confirm Pick Location": "Confirmar Local de Retirada",
    "Confirm Drop Location": "Confirmar Local de Destino",
    "Confirm New Location": "Confirmar Novo Local",
    "Receiver Info": "Informações do Destinatário",
    "Mobile Number": "Número do Celular",
    "Confirm Details": "Confirmar Detalhes",
    "Add Stop": "Adicionar Parada",
    "Sender Info": "Informações do Remetente",
    "Pickup Contact": "Contato de Retirada",
    "Choose Goods Type": "Escolher Tipo de Mercadoria",
    "Loose": "Solta",
    "Qty with unit": "Quantidade com unidade",
    "Goods Type": "Tipo de Mercadoria",
    "Ride Now": "Viagem Agora",
    "Book for Later": "Reservar para Depois",
    "Tap to add Shipment Image": "Toque para adicionar Imagem do Envio",
    "Tap to edit Shipment Image": "Toque para editar Imagem do Envio",
    "Tap to add Unload Image": "Toque para adicionar Imagem de Descarga",
    "Tap to edit Unload Image": "Toque para editar Imagem de Descarga",
    "Upload Unload Proof": "Enviar Comprovante de Descarga",
    "Upload Shipment Proof": "Enviar Comprovante de Envio",
    "Owner": "Proprietário",
    "Transport": "Transporte",
    "Delivery": "Entrega",
    "Waiting For Payment": "Aguardando Pagamento",
    "Continue with": "Continuar com",
    "Goto URL": "Ir para URL",
    "Register for": "Registrar para",
    "Recommended Fare": "Tarifa Recomendada",
    "Offer Your Fare": "Ofereça Sua Tarifa",
    "Offered ride fare": "Tarifa de corrida oferecida",
    "Current Fare": "Tarifa Atual",
    "Update": "Atualizar",
    "You are Off Duty now": "Você está fora de serviço agora",
    "Are you sure want to cancel the ride?": "Tem certeza de que deseja cancelar a corrida?",
    "Waiting For Ride Request": "Aguardando Solicitação de Corrida",
    "Skip the Ride": "Pular a Corrida",
    "Bid": "Lance",
    "Waiting for user to accept the request": "Aguardando o usuário aceitar a solicitação",
    "Pick Up": "Retirada",
    "Get ride from distance between": "Obter corrida de distância entre",
    "Create Request": "Criar Solicitação",
    "your fare must not be lesser than recommended fare": "sua tarifa não deve ser menor que a tarifa recomendada",
    "Contact Us": "Entre em Contato",
    "Sign In with Email": "Entrar com E-mail",
    "Email Verification": "Verificação de E-mail",
    "Select Theme": "Selecionar Tema",
    "New version of this app is available in store, please update the app for continue using": "Nova versão deste aplicativo está disponível na loja, por favor atualize o aplicativo para continuar usando",
    "You can choose more than 1 vehicle types": "Você pode escolher mais de 1 tipo de veículo",
    "Bidding": "Lance",
    "The selected contact will be added in our server for SOS purpose, In app there is an option to remove this contacts.": "O contato selecionado será adicionado em nosso servidor para fins de SOS. No aplicativo há uma opção para remover estes contatos.",
    "Payment Recieved": "Pagamento Recebido",
    "What's Your Email ?": "Qual é o seu e-mail?",
    "Taxi": "Táxi",
    "Both": "Ambos",
    "What's your service location": "Qual é o seu local de serviço",
    "Enter 4 letter to search pickup location": "Digite 4 letras para buscar local de retirada",
    "Complaint must be minimum 10 characters": "A reclamação deve ter no mínimo 10 caracteres",
    "Your Account is Declined": "Sua Conta foi Recusada",
    "Declined Reason": "Motivo da Recusa",
    "Skip Referral": "Pular Indicação",
    "Referral (Optional)": "Indicação (Opcional)",
    "Your wallet balance is low try another payment method": "O saldo da sua carteira está baixo, tente outro método de pagamento",
    "Provided mobile number already taken": "O número de celular fornecido já está em uso",
    "Mobile": "Celular",
    "Chat With Us": "Conversar Conosco",
    "Admin Chat": "Chat do Administrador"
}

def translate_pt_br_section(file_path):
    """Traduz a seção pt_BR do arquivo translation.dart"""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Encontrar a seção pt_BR
    pt_br_start = content.find('  "pt_BR": {')
    if pt_br_start == -1:
        print("Seção pt_BR não encontrada!")
        return
    
    # Encontrar o final da seção pt_BR
    pt_br_end = content.find('\n  }\n};', pt_br_start)
    if pt_br_end == -1:
        pt_br_end = content.find('\n  }', pt_br_start)
    
    if pt_br_end == -1:
        print("Fim da seção pt_BR não encontrado!")
        return
    
    pt_br_section = content[pt_br_start:pt_br_end]
    
    # Traduzir cada string
    for en_text, pt_text in translations.items():
        # Escapar caracteres especiais para regex
        en_escaped = re.escape(en_text)
        # Substituir apenas dentro da seção pt_BR
        pattern = f'(": "{en_escaped}")'
        replacement = f'": "{pt_text}"'
        pt_br_section = re.sub(pattern, replacement, pt_br_section)
    
    # Substituir a seção no conteúdo original
    new_content = content[:pt_br_start] + pt_br_section + content[pt_br_end:]
    
    # Salvar o arquivo
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print("Tradução concluída!")

if __name__ == "__main__":
    translate_pt_br_section("lib/translation/translation.dart")
