// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCceQTKfoIsPblC4vWMyxC8HfaVUKc0U5U',
    appId: '1:725859983456:web:7d738c80d0d3e3376c2305',
    messagingSenderId: '725859983456',
    projectId: 'goin-7372e',
    authDomain: 'goin-7372e.firebaseapp.com',
    databaseURL: 'https://goin-7372e-default-rtdb.firebaseio.com',
    storageBucket: 'goin-7372e.firebasestorage.app',
    measurementId: 'G-RX7QR1W5W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQfTS6lgiK2E1iOYmQj6Mm63j0I27N9N4',
    appId: '1:725859983456:android:60783efc6be48da66c2305',
    messagingSenderId: '725859983456',
    projectId: 'goin-7372e',
    authDomain: 'goin-7372e.firebaseapp.com',
    databaseURL: 'https://goin-7372e-default-rtdb.firebaseio.com',
    storageBucket: 'goin-7372e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfTS6lgiK2E1iOYmQj6Mm63j0I27N9N4',
    appId: '1:725859983456:ios:default',
    messagingSenderId: '725859983456',
    projectId: 'goin-7372e',
    databaseURL: 'https://goin-7372e-default-rtdb.firebaseio.com',
    storageBucket: 'goin-7372e.firebasestorage.app',
    iosBundleId: 'br.app.omny.user',
  );
}
